spring:
  application:
    name: yzfwh
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

server:
  port: 9101
zb:
  rest:
    enabled: true
swagger:
  enabled: true
  base-package: com.zb.byb.controller
  title: 帮养宝养户服务号
  version: 1.0.0.SNAPSHOT
  description: 帮养宝养户服务号API

wx:
  appId: wx33ceaedab9a6ed8f
  appsecret: 4c83cdaed8d11e54d447a421a5923202
  token: Hfjd334Hdsncb873KjdNf322

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true